language: python

python:
- "2.7"
- "3.4"

install:
- pip install cheetah
- pip install twisted
- pip install pyopenssl

script: 
- python -m compileall -l . -l plugin -l plugin/backport -l plugin/controllers -l plugin/controllers/models

